# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "centos/7"
  config.ssh.insert_key = false
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision :shell, :path => "bootstrap.sh"

  config.vm.define :node1 do |node1|
    node1.vm.hostname = "node1.influxdata.com"
    node1.vm.network :private_network, ip: "192.168.70.101"
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 2048] # RAM allocated to each VM
      vb.name = "Influx Node1"
    end
  end

  config.vm.define :node2 do |node2|
    node2.vm.hostname = "node2.influxdata.com"
    node2.vm.network :private_network, ip: "192.168.70.102"
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 2048] # RAM allocated to each VM
      vb.name = "Influx Node2"
    end
  end

  config.vm.define :node3 do |node3|
    node3.vm.hostname = "node3.influxdata.com"
    node3.vm.network :private_network, ip: "192.168.70.103"
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 2048] # RAM allocated to each VM
      vb.name = "Influx Node3"
    end
  end
end

#(1..3).each do |i|
#  config.vm.define "node-#{i}" do |node|
#    node.vm.provision "shell",
#      inline: "echo hello from node #{i}"
#  end
#end
